dependency:
  name: galaxy

driver:
  name: default

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
        ansible_become: false
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

scenario:
  name: upgrade_mail_sentinel_scheduler
  test_sequence:
    - prepare
    - converge
    - verify
